services:
  db:
    container_name: connect-four-db
    image: postgres:16.3-alpine3.20
    restart: always
    volumes:
      - ${ROOT_FOLDER}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}

  backend:
    container_name: connect-four-backend
    build:
      context: ./backend
      args:
        - DEV=${DEBUG}
    restart: always
    volumes:
      - ${ROOT_FOLDER}/static:/vol/web
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_PORT=${API_PORT}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DEBUG=${DEBUG}
      - LOAD_SAMPLE_DATA=${LOAD_SAMPLE_DATA}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
    depends_on:
      - db

  proxy:
    container_name: connect-four-proxy
    build:
      context: ./proxy
    restart: always
    volumes:
      - ${ROOT_FOLDER}/static:/vol/static
    ports:
      - ${API_PORT}:8000
    depends_on:
      - backend