# Generated by Django 5.0.7 on 2024-07-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='session_id',
        ),
    ]
