# Generated by Django 5.0.7 on 2024-07-23 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_guest_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Username must be alphanumeric or contain underscores only.', regex='^[a-zA-Z0-9_]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Username must be alphanumeric or contain underscores only.', regex='^[a-zA-Z0-9_]*$')]),
        ),
    ]
