# Generated by Django 5.0.7 on 2024-07-23 19:16

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_guest_username_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.IntegerField(default=6)),
                ('columns', models.IntegerField(default=7)),
                ('board', models.JSONField(default=core.models.default_board)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='current_turn', to='core.player')),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_one', to='core.player')),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player_two', to='core.player')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.status')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='winner', to='core.player')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['game_id'],
            },
        ),
    ]
