# Generated by Django 5.0.7 on 2024-07-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_game_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
