# Generated by Django 5.0.7 on 2024-07-25 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_player_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMakingQueue',
            fields=[
                ('queue_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_preference', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('random', 'Random')], default='random', max_length=6)),
                ('matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'verbose_name': 'Match Making Queue',
                'verbose_name_plural': 'Match Making Queues',
                'ordering': ['queue_id'],
            },
        ),
    ]
