# Generated by Django 5.0.7 on 2024-07-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_matchmakingqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingqueue',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game'),
        ),
    ]
