# Generated by Django 5.0.7 on 2024-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_matchmakingqueue_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingqueue',
            name='turn_preference',
        ),
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
