# Generated by Django 5.0.7 on 2024-07-26 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_matchmakingqueue_turn_preference_player_elo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingqueue',
            name='matched',
        ),
        migrations.AddField(
            model_name='matchmakingqueue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.status'),
        ),
    ]
