# Generated by Django 5.0.7 on 2024-07-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_matchmakingqueue_matched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=1200),
        ),
    ]
