# Generated by Django 5.0.7 on 2024-07-27 08:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_player_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Username must contain only lowercase alphanumeric & underscores.', regex='^[a-z0-9_]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Username must contain only lowercase alphanumeric & underscores.', regex='^[a-z0-9_]*$')]),
        ),
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('invitation_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('play_preference', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('random', 'Random')], default='random', max_length=10)),
                ('rows', models.IntegerField(default=6)),
                ('columns', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.player')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.status')),
            ],
            options={
                'verbose_name': 'Game Invitation',
                'verbose_name_plural': 'Game Invitations',
                'ordering': ['invitation_id'],
            },
        ),
    ]
