# Generated by Django 5.0.7 on 2024-07-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_move_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_one', to='core.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_two', to='core.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.status'),
        ),
        migrations.AlterField(
            model_name='gameinvitation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.status'),
        ),
        migrations.AlterField(
            model_name='matchmakingqueue',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.AlterField(
            model_name='matchmakingqueue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.status'),
        ),
    ]
