# Generated by Django 5.0.7 on 2024-07-31 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_game_player_one_alter_game_player_two_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('elo_history_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_elo', models.IntegerField()),
                ('new_elo', models.IntegerField()),
                ('delta', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'verbose_name': 'Elo History',
                'verbose_name_plural': 'Elo Histories',
                'ordering': ['elo_history_id'],
            },
        ),
    ]
