# Generated by Django 5.0.7 on 2024-07-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_elohistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elohistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Elo History', 'verbose_name_plural': 'Elo Histories'},
        ),
    ]
