# Generated by Django 5.0.7 on 2024-08-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_elohistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='code_name',
            field=models.CharField(default='codec', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
