# Generated by Django 5.0.7 on 2024-08-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_game_depth_game_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='elohistory',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.game'),
            preserve_default=False,
        ),
    ]
