# Generated by Django 5.0.7 on 2024-08-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_elohistory_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.player'),
        ),
    ]
